### ISSUE TITLE
panic: math/big: buffer too small to fit value

### ISSUE THREAD

**Issue by wpater** [hyperledger/firefly-signer#59]
During indexing BSC `evmconnect` started to failing with following error:

```
panic: math/big: buffer too small to fit value

goroutine 70 [running]:
math/big.nat.bytes(...)
        /usr/local/go/src/math/big/nat.go:1166
math/big.(*Int).FillBytes(0xc018a0d540, {0xc0257290b0, 0x14, 0x14})
        /usr/local/go/src/math/big/int.go:460 +0xf8
github.com/hyperledger/firefly-signer/pkg/abi.(*Serializer).serializeElementaryType(0xc000037f20, {0x104e6b0, 0xc0001e8680}, {0xc01153d370, 0x9}, 0xc0002987c0)
        /go/pkg/mod/github.com/hyperledger/firefly-signer@v1.1.10-0.20230928181245-a5e84e149fdb/pkg/abi/outputserialization.go:191 +0x433
github.com/hyperledger/firefly-signer/pkg/abi.(*Serializer).walkOutput(0xe124a3?, {0x104e6b0, 0xc0001e8680}, {0xc01153d370, 0x9}, 0xc0002987c0)
        /go/pkg/mod/github.com/hyperledger/firefly-signer@v1.1.10-0.20230928181245-a5e84e149fdb/pkg/abi/outputserialization.go:175 +0x167
github.com/hyperledger/firefly-signer/pkg/abi.(*Serializer).serializeTuple(0xc000037f20, {0x104e6b0, 0xc0001e8680}, {0x0, 0x0}, 0xc000298780)
        /go/pkg/mod/github.com/hyperledger/firefly-signer@v1.1.10-0.20230928181245-a5e84e149fdb/pkg/abi/outputserialization.go:228 +0x80a
github.com/hyperledger/firefly-signer/pkg/abi.(*Serializer).walkOutput(0xc00004e020?, {0x104e6b0, 0xc0001e8680}, {0x0, 0x0}, 0xc000298780)
        /go/pkg/mod/github.com/hyperledger/firefly-signer@v1.1.10-0.20230928181245-a5e84e149fdb/pkg/abi/outputserialization.go:179 +0x10d
github.com/hyperledger/firefly-signer/pkg/abi.(*Serializer).SerializeJSONCtx(0xc000475b20?, {0x104e6b0, 0xc0001e8680}, 0xc00362c000?)
        /go/pkg/mod/github.com/hyperledger/firefly-signer@v1.1.10-0.20230928181245-a5e84e149fdb/pkg/abi/outputserialization.go:162 +0x5a
```

more details on https://discord.com/channels/905194001349627914/928377875827154984/1194272891957694614

**Comment by wpater** [comment]
should be resolved by https://github.com/hyperledger/firefly-signer/pull/56

**Comment by wpater** [comment]
verified on BSC chain - should be fine
